dist: xenial
language: python

python:
  - "3.7"
  - "3.8"

services:
  - postgresql

install:
  - pip install pipenv
  - make init

before_script:
  - psql -c 'create database skidon;' -U postgres

env:
  global:
    - ENV_FOR_DYNACONF=travis

script:
  - make test
