# Generated by Django 3.0.3 on 2020-02-19 16:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Katalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(unique=True)),
                ("content", models.TextField(unique=True)),
                ("media", models.URLField(unique=True)),
                ("adress", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Katalog", "ordering": ["title"]},
        )
    ]
