# Generated by Django 3.0.3 on 2020-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '1000_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.URLField(unique=True)),
                ('shop', models.TextField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Discount',
                'ordering': ['shop'],
            },
        ),
    ]
