# Generated by Django 3.0.3 on 2020-02-19 20:07

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("about", "1002_auto_20200219_2255")]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(unique=True)),
                ("content", models.TextField(unique=True)),
                ("media", models.URLField(unique=True)),
                ("at", models.DateField()),
                (
                    "post_kateg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="about.Post_kateg",
                    ),
                ),
            ],
        )
    ]
