# Generated by Django 3.0.4 on 2020-03-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='additional_media',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='media',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='shop',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
