# Generated by Django 3.0.4 on 2020-03-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '1111_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['media'], 'verbose_name_plural': 'Discount'},
        ),
    ]
