# Generated by Django 3.0.4 on 2020-03-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("about", "1112_auto_20200309_0103")]

    operations = [
        migrations.AlterField(
            model_name="post_kateg", name="name", field=models.TextField()
        )
    ]
