default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG:  True
  SECRET_KEY: ""
  TELEGRAM_SKIDON_TOKEN: ""

heroku:
  DEBUG: True
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - skidon.herokuapp.com

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost



