default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG:  True
  SECRET_KEY: ""
  TELEGRAM_SKIDONBOT_TOKEN: ""

heroku:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - skidon.herokuapp.com
  DEBUG: True

development:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  DEBUG: true
  SECRET_KEY: "xxx"
  TELEGRAM_SKIDONBOT_TOKEN: "bot"

travis:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  DATABASE_URL: "postgresql://postgres@localhost:5432/skidon"
  DEBUG: true
  SECRET_KEY: "xxx"
  TELEGRAM_SKIDONBOT_TOKEN: "bot"
