default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG:  True
  SECRET_KEY: ""
  TELEGRAM_SKIDON_TOKEN: ""

heroku:
  DEBUG: True
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - skidon.herokuapp.com
    - skidon.herokuapp.com/telegram

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost

travis:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  SECRET_KEY: "xxx"
  DATABASE_URL: "postgresql://postgres@localhost:5432/skidon"



