default:
  SECRET_KEY: ""
  DEBUG:  true
  ALLOWED_HOSTS: []
  DATABASE_URL: ""

heroku:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - skidon.herokuapp.com

development:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost

travis:
   DEBUG: true 
   ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
   SECRET_KEY: "xxx"
   DATABASE_URL: ""



